--ALTERAR DO CDB CCB PARA O PDB XEPDB1

ALTER SESSION SET CONTAINER = XEPDB1;


-- CRIANDO TABLESPACE
CREATE TABLESPACE nome_tablespace
 DATAFILE
   'C:\app\Jardel\product\18.0.0\oradata\XE\XEPDB1\Nome_tablespace.dbf' 
		SIZE 100m AUTOEXTEND ON NEXT 50m MAXSIZE 500m
   ONLINE
   PERMANENT
   EXTENT MANAGEMENT LOCAL AUTOALLOCATE
   SEGMENT SPACE MANAGEMENT AUTO;
   
--CRIANDO TABLESPACE 2 
       CREATE TABLESPACE 
       NOME_TABLESPACE 
       DATAFILE 'NOME_TABLESPACE.dbf' SIZE 1M ONLINE;

-- CRIANDO USUÁRIO 
   CREATE USER nome_usuario
          IDENTIFIED BY senha_usuario
          DEFAULT TABLESPACE nome_tablespace
          TEMPORARY TABLESPACE temp;
          
--CRIANDO USUÁRIO 2
     CREATE USER Nome_Usuario
          IDENTIFIED BY Senha_Usuario;
		  
		  
-- PERMISSAO PARA USUÁRIO        
  GRANT CREATE SESSION, CONNECT, RESOURCE TO nome_usuário;
  
--ALTERANDO LIMITE DE COTA PARA O USUARIO
  ALTER USER Nome_Usuario QUOTA UNLIMITED ON nome_tablespace;
  
  
  --DELETAR USER 
  DROP USER nome_usuario;
  
  --DELETAR TABLESPACE 
DROP TABLESPACE nome_tablespace
  INCLUDING CONTENTS AND  DATAFILES
    CASCADE CONSTRAINTS;


	
    
    
    