-- DDL  CRIACAO DA TABELA PARA EXERCICIOS

CREATE TABLE JOGADOR(

ID_JOGADOR NUMBER(10) NOT NULL,
NOME VARCHAR2(100) NOT NULL,
POSICAO VARCHAR2(100),
BI VARCHAR(100),
CONSTRAINT PK_JOGADOR PRIMARY KEY(ID_JOGADOR)
);


CREATE TABLE CONTRATADO(

ID_JOGADOR NUMBER (10) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_FIM DATE NOT NULL,
CONSTRAINT PK_CONTRATADO PRIMARY KEY (ID_JOGADOR, DATA_INICIO),
CONSTRAINT FK_CONTRATADO_REF_JOGADOR  FOREIGN KEY (ID_JOGADOR)
REFERENCES JOGADOR (ID_JOGADOR),
CONSTRAINT CK_CONTRATADO CHECK (DATA_FIM > DATA_INICIO)
);


CREATE TABLE FUNCIONARIOS
(
 ID INT NOT NULL,
 NOME VARCHAR2(50) NOT NULL,
 SALARIO DECIMAL(10,2),
 SETOR VARCHAR2(30), 
 PRIMARY KEY (id)
);

CREATE SEQUENCE ID_FUNC
 START WITH     1
 INCREMENT BY   1
 NOCACHE;


-- DML SELECT
-- EXEMPLO SELECT
SELECT * FROM funcionarios;


-- EXEMPLO SELECT
SELECT id,nome,salario,setor AS depto
FROM funcionarios;


-- DML INSERT
INSERT INTO funcionarios (ID,nome,salario) VALUES (ID_FUNC.NEXTVAL,'Pedro',1000);
INSERT INTO funcionarios (ID,nome,salario) VALUES (ID_FUNC.NEXTVAL,'Cleiton',1080);
INSERT INTO funcionarios (ID,nome,salario,setor) VALUES (ID_FUNC.NEXTVAL,'Joao',1000,'');
INSERT INTO funcionarios (ID,nome,salario,setor) VALUES (ID_FUNC.NEXTVAL,'Alexandre',3000,'');
INSERT INTO funcionarios (ID,nome,salario,setor) VALUES (ID_FUNC.NEXTVAL,'Jose',2000,'');


-- simulando erro
INSERT INTO funcionarios (ID,nome,salario) VALUES (ID_FUNC.NEXT_VAL,'Pedro','asasaasas');


-- DML UPDATE
UPDATE funcionarios SET salario = 10000
WHERE id=6;


-- OU Aumento de 50% sobre Salário atual.
UPDATE funcionarios SET salario=salario*1.5
WHERE id='2';


-- exemplo update com mais de um campo
UPDATE funcionarios SET salario=salario*1.5,setor='TI'
WHERE id<>'1';


-- DML DELETE
DELETE
FROM funcionarios
WHERE id='1';


-- DML SELECT EVIDENCIA DA EXCLUSAO
SELECT *
FROM funcionarios;
-- WHERE id='1';


-- RENOMEIA O NOME DA TABELA
ALTER TABLE JOGADORES RENAME TO JOGADOR;

--ADICIONA UM CAMPO NA TABELA
ALTER TABLE JOGADOR ADD APELIDO VARCHAR2(30);

-- RENOMEIA O NOME DO CAMPO
ALTER TABLE JOGADOR RENAME COLUMN APELIDO TO NICKNAME;

--MODIFICA NO TIPO DE DADO DA TABELA
ALTER TABLE JOGADOR MODIFY POSICAO NUMBER(5,0);

--EXCLUIR O NOME DE UM CAMPO DA TABELA
ALTER TABLE JOGADOR DROP COLUMN BI CASCADE CONSTRAINTS;

--EXCLUIR TABLEA 
DROP TABLE JOGADOR;

--EXCLUIR REGRA
ALTER TABLE CONTRATADO
DROP CONSTRAINT FK_FK_CONTRATADO_REF_JOGADOR;

--DESABILITAR A CONTRAINT
ALTER TABLE CONTRATADO DISABLE CONSTRAINT FK_FK_CONTRATADO_REF_JOGADOR;

--ABILITAR A CONTRAINT
ALTER TABLE CONTRATADO ENABLE CONSTRAINT FK_FK_CONTRATADO_REF_JOGADOR;

